### ISSUE TITLE
API Response 401: UNAUTHORIZED; Manual Workflow keeps failing

### ISSUE THREAD

**Issue by diorcula** [athul/waka-readme#102]
I try to test the workflow and readme stats by manually running the workflow from the Actions menu in Github but it keeps failing.

I have added the Waka token as a secret as well as the Github token, 2 separate secrets.

My waka readme yml:
```
name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          #REPOSITORY: <gh_username/gh_username>
```

And this is the output on debugging:
![image](https://user-images.githubusercontent.com/32682696/194070860-bcb236f7-58cc-47c2-8acb-b247f0259b99.png)

Any idea how this is possible?
i just followed the steps on your Github.
