### ISSUE TITLE
Failed to run workflow

### ISSUE THREAD

**Issue by NoNormalCreeper** [athul/waka-readme#117]
The GitHub Actions workflow had run several times successfully in the past.

But when I manually change the `jobs.steps.uses` arguement from `anmol098/waka-readme-stats@master` to `anmol098/waka-readme-stats@V3`, and then run the workflow at 12/22/2022, I found it failed to run -> [log](https://github.com/NoNormalCreeper/NoNormalCreeper/actions/runs/3755322553/jobs/6380276496)

Then I changed the `uses` argument back to `anmol098/waka-readme-stats@master`, but don't work -> [log](https://github.com/NoNormalCreeper/NoNormalCreeper/actions/runs/4220036086)

I thought it was because of timeout in generating the loc chart, so I disabled it, but still don't work -> [log](https://github.com/NoNormalCreeper/NoNormalCreeper/actions/runs/4220057284)

You can check the commit log of [my profile repo](https://github.com/NoNormalCreeper/NoNormalCreeper).

I'll be sincerely appreciative if you can take time out of your busy schedule to solve my problem.

**Comment by joe733** [comment]
Hi @NoNormalCreeper, you've referenced the wrong repository in [your workflow file](https://github.com/NoNormalCreeper/NoNormalCreeper/blob/02664497b4e631e36e968ad71c6f2f5e60b672d8/.github/workflows/waka-readme.yml#L12-L14)

```yml
...
    steps:
      - uses: anmol098/waka-readme-stats@master
...
```

It should be this instead.

```yml
...
    steps:
      - uses: athul/waka-readme@master
...
```

And

```yml
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LOC_CHART: "False"
```

You do not need `GH_TOKEN: ${{ secrets.GH_TOKEN }}` on profile readme. Provide `true` instead of `"True"` in YAML.

---

I think you've got the wrong project. Please refer to https://github.com/athul/waka-readme#readme, if you want to use `athul/waka-readme`
