### ISSUE TITLE
Readme stats generated but readme not updated

### ISSUE THREAD

**Issue by naveen8801** [athul/waka-readme#118]
### Description

![image](https://user-images.githubusercontent.com/54985099/220023179-4baffc4b-b303-4e1d-8483-afe7c6c5a7d9.png)

As we can see in the logs stats were generated but the readme was not updated. I've followed all the steps to use this action. Link to my repo is here - [link](https://github.com/naveen8801/naveen8801)

https://github.com/naveen8801/naveen8801

**Comment by joe733** [comment]
Can you check your workflow permissions https://github.com/athul/waka-readme/issues/114#issuecomment-1398216058?

**Comment by naveen8801** [comment]
Hey @joe733 , 
![image](https://user-images.githubusercontent.com/54985099/220064133-1091fd38-491f-4bb8-8f0a-19e8569a873a.png)

**Comment by joe733** [comment]
Can you wait for a day or two. After WakaTime fetches new data, it should get populated automatically.

**Comment by naveen8801** [comment]
yep sure @joe733 , thanks for helping  👍

**Comment by joe733** [comment]
Hi @naveen8801, in your profile `README.md`, you've given

```md
<!--START_SECTION:SECTION_NAME -->
<!--END_SECTION:SECTION_NAME -->
```

`SECTION_NAME` is just a placeholder, instead if you provide, say:

```md
<!--START_SECTION:stats-->
<!--END_SECTION:stats-->
```

`SECTION_NAME` must be set to `stats` in the [`waka-readme.yml`](https://github.com/naveen8801/naveen8801/blob/master/.github/workflows/waka-readme.yml) file:

```yml
...
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
          SECTION_NAME: "stats"
...
```

The default is `waka`, which if given in README, you do not need to set `SECTION_NAME` in the `workflow.yml` file.


```md
<!--START_SECTION:waka-->
<!--END_SECTION:waka-->
```

> **Note**: There is no space between `waka` or `stats` and the  `-->` symbol (e.g. `stats-->`).
