### ISSUE TITLE
Flow fails and says 401 Bad Cred

### ISSUE THREAD

**Issue by KhamkhaDeveloper** [athul/waka-readme#13]
Hey Athul, Congrats on developing this Github Action, Its Really Cool. Though I am facing some issue integrating into my profile.
PFA screenshot 

[
<img width="1329" alt="Screenshot 2020-07-19 at 7 54 46 PM" src="https://user-images.githubusercontent.com/67491354/87877051-b5a8ce00-c9f9-11ea-8c1d-24cad7d5a5aa.png">
](url)

Thanks,
Deepak

**Comment by athul** [comment]
Hey @KhamkhaDeveloper 
I checked your Repo and the workflow file. This error message seems to say that there was an Authentication Error. This might happen if you passed a wrong GitHub API Key for executing the Action. The solution I'd say is **to remove the input for the API key for GitHub Actions rather use the API Key given by GitHub Actions itself.**

Some more tips
- Remove the Username input since `USERNAME` will be defaulted to the repository owner's name ,ie your Profile Name
- Remove the `SHOW_TITLE` input since it will be defauled to `false`. If you want to include the Week number and Week in your metrics you can set `SHOW_TITLE: true` else just skip this input.
- Here is the best option for refactoring your workflow file to
```yml
name: Update stats

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0/2 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
```

Good Hack on Adding the `workflow_dispatch` for triggering the action manually. Make sure to add your Wakatime API Key to your Repo Secrets and you can get your API key for Wakatime from https://wakatime.com/settings/account
