### ISSUE TITLE
 522 CRITICAL 404 {"message": "Not Found"

### ISSUE THREAD

**Issue by PaulMargueritteOclockStudent** [athul/waka-readme#140]
I use the script in my readme repository, here is the full error code

![image](https://github.com/athul/waka-readme/assets/122986913/910be63b-3a32-4e5b-a468-5ea0f0ce9460)

**Comment by joe733** [comment]
```yml
...
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: athul/athul
...
```

Please use your repository name `PaulMargueritteOclockStudent/PaulMargueritteOclockStudent` in your [workflow](https://github.com/PaulMargueritteOclockStudent/PaulMargueritteOclockStudent/blob/b7f1bba73557ef7f9d917a303cf43e8ee8136592/.github/workflows/wakaa-readme.yml#L20).

> I should probably make a note in [Readme#Example](https://github.com/athul/waka-readme#example).
