### ISSUE TITLE
The IGNORED_LANGUAGES argument does not work

### ISSUE THREAD

**Issue by mengxi-ream** [athul/waka-readme#166]
```yaml
name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 6 AM Vancouver time (13:00 UTC)
    - cron: "0 13 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: true # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML JSON TOML Markdown MDX # optional
          TIME_RANGE: last_30_days # optional
          ### commit
          AUTHOR_NAME: MengXi # optional
          # you can populate email-id with secrets instead
```
