### ISSUE TITLE
IGNORED_LANGUAGES Option is not working

### ISSUE THREAD

**Issue by urdekcah** [athul/waka-readme#167]
```yaml
name: ОБНОВЛЕНИЕ СТАТИСТИКИ WAKATIME

on:
  workflow_dispatch:
  schedule:
    # Этот workflow будет запускаться КАЖДЫЙ ЧАС
    - cron: "0 */1 * * *"

jobs:
  update-readme:
    name: urdekcah
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          SHOW_TOTAL: true
          IGNORED_LANGUAGES: YAML JSON TOML MARKDOWN GIT
          COMMIT_MESSAGE: Обновлен файл readme с новыми метриками графика wakatime
```
I apologize for creating an issue with the same content as issue #166, but I tried to use `IGNORED_LANGUAGES` to remove certain languages from the table, but it doesn't seem to work as expected.
![image](https://github.com/user-attachments/assets/24474ec9-03ef-4101-82b1-489d79beaed7)
