### ISSUE TITLE
Hi, I still have problem with using it.

### ISSUE THREAD

**Issue by Stanley-Yao** [athul/waka-readme#17]
I really love this cool project. While I am trying that I have a problem with rendering the stuff in my personal Profile `Readme.md`
My code is like the following:

```
<!--START_SECTION:waka-->

....
....

name: Waka Readme
on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ MY-WAKA-TIME-API-KEY }}
<!--END_SECTION:waka-->
```

Thanks for your help.

**Comment by athul** [comment]
Hey @Stanley-Yao ,
Is it possible to point us to the repo where the action is being run?

If it isn't being run anywhere try these methods
- Copy the WakaTime API key and paste it in the repo secrets
- After copying it in the secrets go here → https://github.com/Stanley-Yao/Stanley-Yao/actions and create a new workflow
- Replace the contents with the above code

```yml
name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ MY-WAKA-TIME-API-KEY }
```
I added `workflow_dispatch` for you to manually trigger the workflow. 

That's it. If this method didn't work. Please do keep us posted

**Comment by athul** [comment]
Hey @Stanley-Yao 
I checked your repo and please don't save your  api key in the file itself. This is due to security issues. Save it in your repo secrets https://github.com/Stanley-Yao/Stanley-Yao/settings/secrets

Here is a reference of the yml file I use
```yml
# This is a basic workflow to help you get started with Actions

name: Waka Readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
```
