### ISSUE TITLE
Can support custom repo?

### ISSUE THREAD

**Issue by saltbo** [athul/waka-readme#31]
https://github.com/athul/waka-readme/blob/aaff45b1d4b4629eec06b3fca64a56e40b10ee5c/main.py#L91

**Comment by saltbo** [comment]
I want to use it in my other repo

**Comment by athul** [comment]
Hey, that is totally possible too. At the inception of this project, I was only thinking to add it in the Profile repo. If you'd like to contribute on this. I could walk you through it since I have a bit of stuff to do.

**Comment by saltbo** [comment]
Okay, I will commit a PR later

**Comment by athul** [comment]
Oh cool. 
* Add a new Flag in the `actions.yml` file. It should have a description and default value. It should look something like this(this is an example)
```yml
  COMMIT_MESSAGE:
    description: "Add a commit message of your choice"
    default: "Updated the Graph with new Metrics"
    required: false
```
* In the `main.py` file. Load the value of the flag as an environment variable. In the entrypoint(`__name__=='main'`) add an else if condition to check the value and if it isn't the default repo, callback to the user defined one(or vice versa).

If you've got any queries, feel free to comment on this issue or the related PR
