### ISSUE TITLE
Last 2 weeks of coding activity

### ISSUE THREAD

**Issue by nelson6e65** [athul/waka-readme#33]
There is a way to use 14 days instead of just 1 week?

**Comment by athul** [comment]
I don't think that's possible since wakatime's API  doesn't support that.

https://wakatime.com/developers#stats

**Comment by nelson6e65** [comment]
Thanks for your answer.

There is a way to use it 2 times? 😅 Maybe an option to configure the labels:
```
<!--START_SECTION:waka_weekly-->
// Updated one a week
<!--END_SECTION:waka_weekly-->

<!--START_SECTION:waka_daily-->
// Updated daily
<!--END_SECTION:waka_daily-->
```

So I can run the cron to keep weekly stats from Monday to Sunday on last week, and other daily cron, showing last 7 days stats.

**Comment by ryul1206** [comment]
I just came up with a fun trick to make this possible.
Even if the API doesn't support the `last_14_days` feature, we can get it if the history is recorded in the readme file or a separate file.

For example, let's assume we have `waka-buffer.yaml` in our repo.
```yaml
---
weekly_history:
- start_date: 1 Jan, 2021
  # end_date: 7 Jan, 2021
  logs:
    Python: 5hrs 10mins
    Text: 30mins
- start_date: 2 Jan, 2021
  # end_date: 8 Jan, 2021
  logs:
    Python: 10hrs
    Cpp: 3hrs
- ...(omitted)...
- start_date: 8 Jan, 2021
  # end_date: 14 Jan, 2021
  logs:
    Cpp: 10hrs
    Ruby: 5hrs
```
And if today is January 15, 2021, we can find the records for days 1-14 as follows:
```text
Week: 1 June, 2021 - 14 June, 2021

Cpp   10 hrs  ....... ## %
Python   5 hrs 10 mins ....... ## %
Ruby   5 hrs ...... ## %
```
Percentages can also be calculated by figuring out the weekly totals. This is a bit cumbersome but not impossible.
