### ISSUE TITLE
README not updating daily

### ISSUE THREAD

**Issue by rajitbanerjee** [athul/waka-readme#43]
I don't know why, but for quite a few weeks, the waka readme stats have not been updating at 00:00 UTC as mentioned in the cron job. They only work with a push to the master branch.
Here's my workflow file `main.yml`:
```
name: Waka Readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update README with metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
```
