### ISSUE TITLE
Option to include "other" languages in total time stat

### ISSUE THREAD

**Issue by Eroxl** [athul/waka-readme#80]
I would really appreciate the option to be able to include the other languages in my coding stats for my profile. It's not a large change in the times but I would like it to have all of my coding time included in it.

This should be pretty easy to implement by using `human_readable_total_including_other_language` instead of `human_readable_total` if the parameter is provided.

Not sure what a great name for the parameter is but something like this.
```yml
with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
          INCLUDE_OTHER_TIME_IN_TOTAL: true
```

I would like to implement this if it sounds all right.
